### ISSUE TITLE
Proposal for Enhancing LocalSend's Web Design and Development

### ISSUE THREAD

**Issue by thecodermehedi** [localsend/website#16]
@Tienisto @TheGB0077 

As a beginner web developer, I propose enhancing LocalSend's web design to create a user-friendly landing page. Seeking permission to contribute and collaborate with the team. Excited to learn and grow in the open-source community.

Mehedi Hasan
[![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white)](https://github.com/devbytemehedi) [![Gmail](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:devbytemehedi@gmail.com)

**Comment by Tienisto** [comment]
Sure, you are free to contribute!

**Comment by devbytemehedi** [comment]
@Tienisto thanks. I will start working on it, if you have any specific design features in mind please let me know.

**Comment by Tienisto** [comment]
Thanks. Depending on your free time, you may also rewrite it to some static site generators (Jekyll, Eleventy). Or rewrite partly with Vue + Tailwind. It is up to you :)

**Comment by devbytemehedi** [comment]
Thanks for the response, i will get back to you untill i am somwhat satisfied with my design.
