### ISSUE TITLE
RTL support for new website design

### ISSUE THREAD

**Issue by jermanuts** [localsend/website#49]
Congrats on the website redesign.

I found that the new redesign lack RTL support.

![image](https://github.com/localsend/website/assets/109705802/f5d03cb4-1baf-440f-bbda-b0774fc7cea0)

I think this fixes it https://github.com/nuxt-modules/i18n/issues/762#issuecomment-1058702880, what do you think?

I also think CSS elements need to be fixed too, unless it is handled automatically by Vue/Nuxt?

Ex:
![image](https://github.com/localsend/website/assets/109705802/65eef9f9-c854-4eed-b9cb-e17d924f0d9d)

**Comment by Tienisto** [comment]
Thank you!
I have added RTL support now (basically I replaced `ml-` with `ms-`, and `mr-` with `me-`).
There might be changed needed but I am not familiar with RTL languages.

**Comment by jermanuts** [comment]
All elements look fine except 
![image](https://github.com/localsend/website/assets/109705802/251d200c-1dea-4556-9dae-3706ad189907)

Should be like 

![image](https://github.com/localsend/website/assets/109705802/d4be60de-f032-4d61-a69b-3264201bc793)
