### ISSUE TITLE
The distance between the elements "Download" and "Improve this website" is too large

### ISSUE THREAD

**Issue by sergd88** [localsend/website#62]
The distance between the elements "Download" and "Improve this website" seems too large to me, almost twice as large as the distance used between other elements on the website, and it looks visually unattractive.

![1](https://github.com/localsend/website/assets/125032334/c697d799-4ea0-4709-b7bd-bbd09c50a017)

**Comment by sergd88** [comment]
I perfectly understand that intention was to visually separate the elements more distinctly, so slightly increasing the distance between them, and "Improve this website" itself now relates more to the footer. However, I believe that instead of a 2x distance, we could go with around 1.5x, which I think would look better and still provide enough separation between the elements. Currently, such a large gap really stands out too much.

**Comment by Tienisto** [comment]
Thanks, I've changed that!
